baseurl = "/"
languageCode = "en-us"
title = "rdosreis"
theme = "hugo-lithium"
googleAnalytics = "UA-152719276-1"
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
publishDir = "../rdosreis.github.io"

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "sobre"
    url = "/about/"
[[menu.main]]
    name = "github"
    url = "https://github.com/rdosreis"
[[menu.main]]
    name = "lattes"
    url = "http://lattes.cnpq.br/3867312117732056"
[[menu.main]]
    name = "twitter"
    url = "https://twitter.com/RodrigoSolve"

[params]
    description = "website pessoal"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the FolderRicon, under "static"
    FolderRicon = "FolderRicon.ico"

    [params.logo]
    url = "pvfc_logo.jpg"
    width = 50
    height = 50
    alt = "Logo"

